# Generated by Django 5.1.1 on 2024-10-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('primary_category', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
            ],
        ),
    ]
